server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgis/postgis
    username: postgis
    password: postgis
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
  api-docs:
    path: /api-docs